#Configuraciones de Oauth2 y Keycloack
#Direccion del reino en keycloack
spring.security.oauth2.resource.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI}
#Direccion de las llaves publicas de Keycloack
spring.security.oauth2.resource.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI}

#Configuracion de eureka client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/



spring.cloud.loadbalancer.ribbon.enabled=false

#Configuracion de gateway
spring.cloud.gateway.server.webflux.routes[0].id=microservicio-vehiculo
spring.cloud.gateway.server.webflux.routes[0].uri=lb://MICROSERVICIO-VEHICULO
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/parkimetro/**

